apiVersion: v1
kind: PersistentVolume
metadata:
  name: roster-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/roster
    server: 10.0.0.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roster-pvc
  namespace: roster
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
